#!/bin/sh
opkg update
wget https://op.supes.top/packages/aarch64_generic/luci-app-ttnode_git-21.361.69956-1fc1d61_all.ipk
opkg install luci-app-ttnode_git-21.361.69956-1fc1d61_all.ipk
rm luci-app-ttnode_git-21.361.69956-1fc1d61_all.ipk
